/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uppercaseToLowercaseStream;

import java.io.FilterInputStream;
import java.io.IOException;
import java.io.InputStream;

public class LowerCaseInputStream extends FilterInputStream {
  public LowerCaseInputStream(InputStream in) {
    super(in);
  }

  public int read() throws IOException {
    int readByte = super.read();
    return (readByte == -1 ? readByte : Character.toLowerCase((char) readByte));
  }

  public int read(byte[] b, int offset, int len) throws IOException {
    int result = super.read(b, offset, len);

    for (int i = offset; i < offset + result; i++) {
      b[i] = (byte) Character.toLowerCase((char) b[i]);
    }
    return result;
  }
}
