/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simpleFactoryPattern;

public class App {
  public String getGreeting() {
    return "Welcome to my pizza store.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
