/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package orderSystem;

public class App {
  public String getGreeting() {
    return "Hello, welcome to my resturant.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    var master = new MasterCook();
    var john = new Customer();
    var order = john.makeOrder(master);
    var waiter = new Waiter();
    waiter.takeOrder(order);
  }
}
