/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpgGame;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    // System.out.println(new App().getGreeting());

    Character king = new King();
    Character troll = new Troll();

    troll.attack();
    king.attack();

    king.attack();
    king.setWeapon(new AxeBehavior());
    king.attack();
    troll.attack();
  }
}
