/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withPattern;

public class App {
    public String getGreeting() {
        return "Welcome to my coffee store.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        /// make a coffee
        var dark = new DarkRoast();
        var mocha = new Mocha(dark);
        var milk = new Milk(mocha);
        Milk cf= new Milk(milk);

        System.out.println(cf.getDescription());

        System.out.println(cf.cost());
    }
}
