/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MenuPrint;

public class App {
  public String getGreeting() {
    return "Hello menu print.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    var pancakeHouseMenu = new PancakeHouseMenu();
    var dinerMenu = new DinerMenu();
    var waitress = new Waitress(pancakeHouseMenu, dinerMenu);

    waitress.printMenu();
  }
}
