/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HomeTheater;

public class App {
  public String getGreeting() {
    return "Welcome to home theater system.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    var amp = new Amplifier();
    var cd = new CDPlayer();
    var dvd = new DVDPlayer();
    var popper = new PopcornPopper();
    var proj = new Projector();
    var screen = new Screen();
    var tuner = new Tuner();

    var theater = new HomeTheaterFacade(amp, tuner, dvd, cd, proj, screen, popper);

    theater.watchMovie();
    theater.endMovie();

    theater.listenToCD();
    theater.endCD();

    theater.listenToRadio();
    theater.endRadio();
  }
}
