/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withPattern02;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    // System.out.println(new App().getGreeting());

    var data = new WeatherData();
    var condition = new ConditionDisplay();

    data.subscribe(condition);
  }
}
