/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withOutPattern;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    Duck d = new Duck();

    System.out.println(d.quack());
    System.out.println(d.swim());
    System.out.println(d.display());
  }
}
