/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withPattern;

public class App {
  public String getGreeting() {
    return "Hello!";
  }

  public static void main(String[] args) {
    Duck mallard = new MallardDuck();

    mallard.performFly();
    mallard.performQuack();

    // should crash
    // Duck redhead = new RedHeadDuck();
    // redhead.performFly();
    // redhead.performQuack();

    // model duck example
    // change its performfly behavior
    Duck model = new ModelDuck();
    model.performFly();
    model.performQuack();

    model.setFlyBehavior(new FlyRocketPowered());
    model.performFly();
  }
}
