/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withPattern;

public class App {
  public String getGreeting() {
    return "Hello!";
  }

  public static void main(String[] args) {
    Duck mallard = new MallardDuck();

    mallard.performFly();
    mallard.performQuack();
  }
}
