/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withPattern01;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    // System.out.println(new App().getGreeting());
    var data = new WeatherData();
    // nothing should happen since no observer yet
    data.measurementChanged();
    var condition = new ConditionDisplay();
    data.registerObserver(condition);
    data.measurementChanged();
    data.registerObserver(new ForecastDisplay());
    data.measurementChanged();
    data.registerObserver(new StatsDisplay());
    data.measurementChanged();

    // remove condition display observer
    data.removeObserver(condition);
    data.measurementChanged();
  }
}
