/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package withOutPattern;

public class App {
  public String getGreeting() {
    return "Welcome to my coffee store.\nPlease let me know what do you want to order:";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println("print all the coffees we have:");

    var houseblend = new HouseBlend();
    houseblend.getDescription();
    System.out.println(String.format("the price for the home blend is %f", houseblend.cost()));

    var roast = new DarkRoast();
    roast.getDescription();
    System.out.println(String.format("the price for the dark roast is %f", roast.cost()));
  }
}
