/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CaffeineBeverage;

public class App {
  public String getGreeting() {
    return "My great caffeine beverage.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    var coffee = new Coffee();
    coffee.prepareRecipe();

    var tea = new Tea();
    tea.prepareRecipe();
  }
}
