/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uppercaseToLowercaseStream;

import static org.junit.Assert.*;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import org.junit.Test;

public class LowerCaseInputStreamTest {
  @Test
  public void testSomeLibraryMethod() {
    var expect = new ByteArrayInputStream("this is cool!".getBytes());
    LowerCaseInputStream in =
        new LowerCaseInputStream(new ByteArrayInputStream("This is COOL!".getBytes()));

    int actualByteRead;
    try {
      do {
        var expectByteRead = expect.read();
        actualByteRead = in.read();
        assertEquals(expectByteRead, actualByteRead);
      } while (actualByteRead != -1);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
