/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GumballMachine;

public class App {
  public String getGreeting() {
    return "Welcome to gumbal store.\n";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    var machine = new GumballMachine(1);

    machine.insertQuarter();
    machine.ejectQuater();
    machine.turnCrank();
    machine.dispense();

    System.out.println("----\n");
    machine.insertQuarter();
    machine.turnCrank();
    machine.dispense();

    System.out.println("----\n");
    machine.insertQuarter();
    machine.turnCrank();
    machine.dispense();
  }
}
